---
server:
    port: 8070
spring:
    application:
        name: configserver
    cloud:
        config:
            server:
                git:
                  uri: https://github.com/ansoumanana/config.git
                  clone-on-start: true
                  default-label: master


                #native:
                    #search-locations: classpath:/config
                   # search-locations: classpath:/config
    profiles:
        #active: native
        active: git
    sleuth:
      sampler:
        rate: 10
        probability: 1
    zipkin:
      baseUrl : http://localhost:9411/
      enabled: true
      locator:
        discovery:
          enabled: true
      #sender:
        #type: rabbit
      #rabbitmq:
        #queue: zipkin
    #rabbitmq:
     # host: localhost
     # port: 5672
     # username: guest
      #password: guest

encrypt:
  key: APODNU3093r2rbjzxcn09u213asdhy08WRFH

#spring.sleuth.sampler.percentage=1
#spring.zipkin.baseUrl=http://localhost:9411/
#spring.zipkin.sender.type=rabbit
#spring.zipkin.rabbitmq.queue=zipkin
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest